
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'INTEGER L_BRACE L_BRACKET RESERVED R_BRACE R_BRACKET SEMICOLON STRUCT TYPE_BOOL TYPE_CSTDINT TYPE_PRIMITIVE_FLOAT TYPE_PRIMITIVE_INT TYPE_STRING TYPE_UNSIGNED VAR_NAMEMESSAGE : PARAMS\n    PARAMS : PARAM\n           | PARAMS PARAM\n    \n    PARAM : TYPE VAR_NAME SEMICOLON\n          | TYPE VAR_NAME ARRAY SEMICOLON\n    \n    TYPE : TYPE_PRIMITIVE_INT\n         | TYPE_PRIMITIVE_FLOAT\n         | TYPE_CSTDINT\n         | TYPE_BOOL\n         | TYPE_STRING\n         | TYPE_UNSIGNED TYPE_PRIMITIVE_INT\n    \n    ARRAY : L_BRACKET INTEGER R_BRACKET\n          | ARRAY L_BRACKET INTEGER R_BRACKET\n    '
    
_lr_action_items = {'TYPE_PRIMITIVE_INT':([0,2,3,10,11,14,17,],[5,5,-2,13,-3,-4,-5,]),'TYPE_PRIMITIVE_FLOAT':([0,2,3,11,14,17,],[6,6,-2,-3,-4,-5,]),'TYPE_CSTDINT':([0,2,3,11,14,17,],[7,7,-2,-3,-4,-5,]),'TYPE_BOOL':([0,2,3,11,14,17,],[8,8,-2,-3,-4,-5,]),'TYPE_STRING':([0,2,3,11,14,17,],[9,9,-2,-3,-4,-5,]),'TYPE_UNSIGNED':([0,2,3,11,14,17,],[10,10,-2,-3,-4,-5,]),'$end':([1,2,3,11,14,17,],[0,-1,-2,-3,-4,-5,]),'VAR_NAME':([4,5,6,7,8,9,13,],[12,-6,-7,-8,-9,-10,-11,]),'SEMICOLON':([12,15,21,22,],[14,17,-12,-13,]),'L_BRACKET':([12,15,21,22,],[16,18,-12,-13,]),'INTEGER':([16,18,],[19,20,]),'R_BRACKET':([19,20,],[21,22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'MESSAGE':([0,],[1,]),'PARAMS':([0,],[2,]),'PARAM':([0,2,],[3,11,]),'TYPE':([0,2,],[4,4,]),'ARRAY':([12,],[15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> MESSAGE","S'",1,None,None,None),
  ('MESSAGE -> PARAMS','MESSAGE',1,'p_MESSAGE','yacc.py',6),
  ('PARAMS -> PARAM','PARAMS',1,'p_PARAMS','yacc.py',11),
  ('PARAMS -> PARAMS PARAM','PARAMS',2,'p_PARAMS','yacc.py',12),
  ('PARAM -> TYPE VAR_NAME SEMICOLON','PARAM',3,'p_PARAM','yacc.py',21),
  ('PARAM -> TYPE VAR_NAME ARRAY SEMICOLON','PARAM',4,'p_PARAM','yacc.py',22),
  ('TYPE -> TYPE_PRIMITIVE_INT','TYPE',1,'p_TYPE','yacc.py',34),
  ('TYPE -> TYPE_PRIMITIVE_FLOAT','TYPE',1,'p_TYPE','yacc.py',35),
  ('TYPE -> TYPE_CSTDINT','TYPE',1,'p_TYPE','yacc.py',36),
  ('TYPE -> TYPE_BOOL','TYPE',1,'p_TYPE','yacc.py',37),
  ('TYPE -> TYPE_STRING','TYPE',1,'p_TYPE','yacc.py',38),
  ('TYPE -> TYPE_UNSIGNED TYPE_PRIMITIVE_INT','TYPE',2,'p_TYPE','yacc.py',39),
  ('ARRAY -> L_BRACKET INTEGER R_BRACKET','ARRAY',3,'p_ARRAY','yacc.py',67),
  ('ARRAY -> ARRAY L_BRACKET INTEGER R_BRACKET','ARRAY',4,'p_ARRAY','yacc.py',68),
]
